{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8sdemo-database.serviceAccountName" . }}
  labels:
{{ include "k8sdemo-database.labels" . | nindent 4 }}
{{- end -}}
