apiVersion: apps/v1
kind: Deployment
metadata:
  name: iphymachine
  labels:
    name: iphymachine
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iphymachine
  template:
    metadata:
      labels:
        name: iphymachine
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        - name: incloudConfigURL
          value: 'incloudmanager-config:32001'
        - name: incloudDbUpdateEnabled
          value: 'false'
        name: iphymachine
        image: 100.2.30.190/incloudos-docker/iphymachine-service:{{ IMAGE_TAG }}
        ports:
          - containerPort: 32900

---
kind: Service
apiVersion: v1
metadata:
  name:  iphymachine
spec:
  selector:
    name: iphymachine
  type: NodePort
  ports:
  - name:  iphymachine-port
    port:  32900
    targetPort:  32900
    nodePort: 32900
