apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: icm-ui-ingress
spec:
  rules:
  - host: icm-ui.icm.com
    http:
      paths:
      - backend:
          serviceName: {{ include "icm-ui.fullname" . }}
          servicePort: 80
  tls:
  - secretName: ingress-cert