apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "incloudmanager-api-gateway-regions.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: svc-port
{{- if .Values.debug.enable }}
    - port: {{ .Values.debug.nodePort }}
      {{- if eq .Values.debug.type "NodePort" }}
      nodePort: {{ .Values.debug.nodePort }}
      {{- end }}
      targetPort: {{ .Values.debug.port }}
      protocol: TCP
      name: debug-port
{{- end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}


