apiVersion: v1
kind: Secret
metadata:
  name: k8sdemo-secret
  labels:
    app: k8sdemo
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # database password for "root"
  MYSQL_USER_NAME: ZGJ1c2Vy # database user name for "dbuser"
  MYSQL_USER_PASSWORD: ZGJ1c2Vy # database password for "dbuser"