- block:
    - name: 创建icm ingress 证书目录
      file: name=/opt/kube/icm-x509/ state=directory

    - stat: path="/opt/kube/icm-x509/tls.key"
      register: tls_key_result
    - stat: path="/opt/kube/icm-x509/tls.key"
      register: tls_crt_result

    - name: 创建 x509
      shell: "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /opt/kube/icm-x509/tls.key -out /opt/kube/icm-x509/tls.crt -subj '/CN=icm.com'"
      when: tls_key_result.stat.isreg is not defined or tls_crt_result.stat.isreg is not defined
      run_once: true
      
    - name: 获取所有已经创建的 secret 信息
      command: "{{ bin_dir }}/kubectl get secret --all-namespaces"
      register: secret_info
  delegate_to: "{{ groups.deploy[0] }}"
  run_once: true
- block:
    - name: 创建 ingress-cert 部署
      shell: "{{ bin_dir }}/kubectl -n kube-system create secret tls ingress-cert --key=/opt/kube/icm-x509/tls.key --cert=/opt/kube/icm-x509/tls.crt"
      delegate_to: "{{ groups.deploy[0] }}"
      run_once: true
  when: '"ingress-cert" not in secret_info.stdout'
