apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8sdemo-backend.fullname" . }}
  labels:
    {{- include "k8sdemo-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8sdemo-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8sdemo-backend.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "k8sdemo-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_USER_NAME
              value: {{ .Values.global.mysqlUserName }}
            - name: MYSQL_USER_PASSWORD
              value: {{ .Values.global.mysqlUserPassword }}
            - name: MYSQL_HOST
              value: {{ .Values.global.mysqlHost }}
            - name: MYSQL_PORT
              value: "{{ .Values.global.mysqlPort }}"
            - name: MYSQL_DATABASE
              value: {{ .Values.global.mysqlDatabase }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.deployment.volumeName }} #k8sdemo-backend-persistentstorage
              mountPath: /logs
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: {{ .Values.deployment.volumeName }} # k8sdemo-backend-persistentstorage
        persistentVolumeClaim:
          claimName: {{ .Values.persistentvolumeclaim.name }} # k8sdemo-backend-pvclaim
