apiVersion: v1
kind: Service
metadata:
  name: {{.Values.global.k8sdemoBackendService}}
  labels:
    {{- include "k8sdemo-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{.Values.service.nodePort}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8sdemo-backend.selectorLabels" . | nindent 4 }}
