{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8sdemo-backend.serviceAccountName" . }}
  labels:
{{ include "k8sdemo-backend.labels" . | nindent 4 }}
{{- end -}}
