{{- if .Values.manifests.job_db_init }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-db-init
  lables:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
  annotations:
    # 注意，如果没有下面的这个注释的话，当前的这个Job就会被当成release的一部分
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}
        version: {{ .Chart.Version }}
    spec:
      restartPolicy: Never
      containers:
      - name: post-db-init
        image: "{{ .Values.imagePluginIcm.repository }}/{{ .Values.imagePluginIcm.image }}:{{ .Values.imagePluginIcm.tag }}"
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: incloudConfigURL
          value: '{{ .Values.incloudConfigURL.url }}:{{ .Values.incloudConfigURL.port }}'
        - name: incloudDbUpdateEnabled
          value: 'true'

{{- end }}
