{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8sdemo.serviceAccountName" . }}
  labels:
{{ include "k8sdemo.labels" . | nindent 4 }}
{{- end -}}
