# tiller_image: gcr.io/kubernetes-helm/tiller:v2.12.0
tiller_image: "{{ REG_MIRROR }}gcrio/kubernetes-helm/tiller-{{ ARCH }}:v2.12.3"
# 离线镜像tar包
tiller_offline: "tiller_v2.12.3.tar"

helm_namespace: kube-system
helm_cert_cn: helm001
tiller_sa: tiller
tiller_cert_cn: tiller001
repo_url: https://kubernetes-charts.storage.googleapis.com
# 如果默认官方repo 网络访问不稳定可以使用如下的阿里云镜像repo
#repo_url: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts
