# efk 标签
- name: 设置node节点role
  shell: "{{ bin_dir }}/kubectl label node {{ inventory_hostname }} beta.kubernetes.io/fluentd-ds-ready=true --overwrite"
  when: '"elasticsearch" not in pod_info.stdout and "kibana" not in pod_info.stdout and "fluentd" not in pod_info.stdout and efk_install == "yes"'

- block:
    - name: 尝试推送离线 efk 镜像（若执行失败，可忽略）
      copy: src={{ base_dir }}/down/{{ efk_offline }} dest=/opt/kube/images/{{ efk_offline }}
      when: 'efk_offline in download_info.stdout'
    
    - name: 获取efk离线镜像推送情况
      command: "ls /opt/kube/images"
      register: image_info     
 
    - name: 导入 efk的离线镜像（若执行失败，可忽略）
      shell: "{{ bin_dir }}/docker load -i /opt/kube/images/{{ efk_offline }}"
      when: 'efk_offline in image_info.stdout'
  when: '"elasticsearch" not in pod_info.stdout and "kibana" not in pod_info.stdout and "fluentd" not in pod_info.stdout and efk_install == "yes"'
  ignore_errors: true

- block:
    - name: 在deploy 节点创建monitor相关目录
      file: path={{ item }} state=directory
      with_items:
      - /opt/kube/
      - /opt/kube/kube-system/
      - /opt/kube/kube-system/efk
    
    - name: 准备 efk 的部署文件 1
      file:
        path: /opt/kube/kube-system/efk/{{ item.path }}
        state: directory
        mode: '{{ item.mode }}'
      with_filetree: ../templates/efk
      when: item.state == 'directory'

    - name: 准备 efk 的部署文件 2
      template:
        src: '{{ item.src }}'
        dest: /opt/kube/kube-system/efk/{{ item.path }}
        mode: '{{ item.mode }}'
      with_filetree: ../templates/efk
      when: item.state == 'file'
      
    - name: 创建 efk部署
      shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/efk/ && {{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/efk/es-dynamic-pv/"

  delegate_to: "{{ groups.deploy[0] }}"
  run_once: true
  when: '"elasticsearch" not in pod_info.stdout and "kibana" not in pod_info.stdout and "fluentd" not in pod_info.stdout and efk_install == "yes"'
