# Default values for iworkflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: harbor.inspur.com
  image: incloudos-docker/iworkflow-service
  tag: latest
  pullPolicy: IfNotPresent

imagePluginIcm:
  repository: harbor.inspur.com
  image: incloudos-docker/ibase-plugin-icm
  tag: latest
  pullPolicy: IfNotPresent
  
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 32602
  nodePort: 32602
resources: {}
  # limits:
  #  cpu: 2
  #  memory: 4Gi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

incloudConfigURL:
  url: incloudmanager-config
  port: 32001
incloudConfigLabel:
  regionName: regionOne

nodeSelector: {}

tolerations: []

affinity: {}

manifests:
  job_db_init: true

debug:
  enable: false
  type: NodePort
  port: 5005
  nodePort: 32622
