apiVersion: v1
kind: ConfigMap
metadata:
  name: icm-ui-configmap

data:
  serviceAddr.json: |
    {
      "serverIp":"incloudmanager-api-gateway-regions:7979",
      "mysql":{
        "host":"galera",
        "port":3306,
        "user":"root",
        "password":"123456a?",
        "database":"ibase"
        },
      "bindip":"0.0.0.0"
        }
