apiVersion: v1
kind: Service
metadata:
  name: k8sdemo-database-service
  labels:
    app: k8sdemo-database
spec:
  type: NodePort
  selector:
    app: k8sdemo-database
  ports:
    - protocol : TCP
      nodePort: 30306
      port: 3306
      targetPort: 3306