apiVersion: apps/v1
kind: Deployment
metadata:
  name: icollector-openstack
  labels:
    name: icollector-openstack
spec:
  replicas: 1
  selector:
    matchLabels:
      name: icollector-openstack
  template:
    metadata:
      labels:
        name: icollector-openstack
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        - name: incloudConfigURL
          value: 'incloudmanager-config:32001'
        - name: incloudDbUpdateEnabled
          value: 'false'
        name: icollector
        image: 100.2.30.190/incloudos-docker/icollector-openstack-service:{{ IMAGE_TAG }}
        ports:
          - containerPort: 32505

---
kind: Service
apiVersion: v1
metadata:
  name:  icollector-openstack
spec:
  selector:
    name: icollector-openstack
  type: NodePort
  ports:
  - name:  icollector-openstack-port
    port:  32505
    targetPort:  32505
    nodePort: 32505
