- name: 创建 registry 相关目录
  file: name={{ item }} state=directory
  with_items:
  - /opt/kube/images
  - /opt/kube/registry
- block:

    - name: 检查是否已下载离线 registry 镜像
      command: "ls {{ base_dir }}/down"
      register: download_info
      connection: local
      run_once: true

    - name: 尝试推送离线 registry 镜像
      copy: src={{ base_dir }}/down/{{ item }} dest=/opt/kube/images/{{ item }}
      when: 'item in download_info.stdout'
      with_items:
      - "{{ registryv2_offline }}"
      ignore_errors: true

    - name: 获取 registry 离线镜像推送情况
      command: "ls /opt/kube/images"
      register: image_info

    - name: 导入 registry 的离线镜像
      shell: "docker load -i /opt/kube/images/{{ item }}"
      when: 'item in image_info.stdout'
      with_items:
      - "{{ registryv2_offline }}"
      ignore_errors: true

    - name: 判断registry是否存在
      shell: docker ps -a |grep {{ registryv2_name }}| wc -l
      register: registryv2
    - name: 复制registry配置文件
      template: src=config.yml.j2 dest=/opt/kube/registry/config.yml
    - name: 启动registryv2
      command: "docker run -d  -p {{ registryv2_port }}:5000 -v /opt/kube/registry/config.yml:/etc/docker/registry/config.yml -v /var/lib/registry:/var/lib/registry --restart=always --name {{ registryv2_name }} {{ registryv2_image }}"
      when: registryv2.stdout == "0" and ARCH != "mips64el"
    - name: 启动registryv2
      command: "docker run -d  -p {{ registryv2_port }}:5000 -v /opt/kube/registry/config.yml:/etc/docker/registry/config.yml -v /var/lib/registry:/home --restart=always --name {{ registryv2_name }} {{ registryv2_image }}"
      when: registryv2.stdout == "0" and ARCH == "mips64el"
    - name: 判断{{ registryv2_name }}状态
      shell: docker ps |grep {{ registryv2_name }}| wc -l
      register: registryv2_status
    - debug: msg={{ registryv2_status.stdout }}
  delegate_to: "{{ groups.deploy[0] }}"
  run_once: true

- name: 添加 hosts 解析
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "registry hosts file"
    line: "{{ groups.deploy[0] }} {{ REG_MIRROR_HTTP }}  # generated by registry hosts file"
