# Default values for icompute-hypervisor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: harbor.inspur.com
  image: incloudos-docker/icompute-hypervisor-service
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 32201
  # wsport: 32266
  nodePort: 32201
  # wsnodePort: 32266
resources: {}
  # limits:
  #  cpu: 2
  #  memory: 4Gi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

incloudConfigURL: 
  url: incloudmanager-config
  port: 32001
incloudConfigLabel:
  regionName: regionOne
  
nodeSelector: {}

tolerations: []

affinity: {}

manifests:
  job_db_init: true

debug:
  enable: false
  type: NodePort 
  port: 5005
  nodePort: 32221
